version: '3.7'
services:
  api-server:
    build: .
    container_name: api-server
    tty: true
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - .:/api-server
    depends_on:
        - db-server

  db-server:
    container_name: db-server
    image: mysql:5.7.29
    restart: always
    ports:
      - '13306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: develop
      MYSQL_USER: develop
      MYSQL_PASSWORD: password